title: Sant’Ana Blog

description: > 
  Sant'Ana personal blog whith article about programming 
  callengens, system adminstration and privacy on the web.

baseurl: ""

url: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - Rakefile
  - Dockerfile

sass:
    sass_dir: _sass
